import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

logger = logging.getLogger(__name__)

TEMPLATE_DIR = Path(__file__).parent / "templates"


def _render_paper_rows(papers: list[dict]) -> str:
    """将论文列表渲染为 HTML 表格行。"""
    rows = []
    for p in papers:
        authors = ", ".join(p["authors"][:5])
        if len(p["authors"]) > 5:
            authors += " et al."
        cats = ", ".join(p["categories"])

        abstract = p["abstract"][:400]
        if len(p["abstract"]) > 400:
            abstract += "..."

        summary_html = ""
        if p.get("summary"):
            summary_html = (
                '<div style="margin-top:8px;padding:8px 10px;'
                "background:#f0f7ff;border-left:3px solid #1a73e8;"
                'font-size:13px;color:#3c4043;line-height:1.5">'
                "<strong>Summary:</strong> " + p["summary"] + "</div>"
            )

        rows.append(f"""
        <tr>
            <td style="padding:10px;border-bottom:1px solid #eee">
                <a href="{p["url"]}" style="color:#1a0dab;font-weight:bold;text-decoration:none">
                    {p["title"]}
                </a>
                <div style="font-size:13px;color:#5f6368;margin-top:4px">
                    {authors}
                </div>
                <div style="font-size:12px;color:#80868b;margin-top:2px">
                    {cats} | {p["published"]} | Score: {p["score"]:.4f}
                </div>
                <p style="font-size:13px;color:#3c4043;margin-top:6px;line-height:1.5">
                    {abstract}
                </p>
                {summary_html}
            </td>
        </tr>""")
    return "\n".join(rows)


def build_email(papers: list[dict], keywords: list[str]) -> str:
    """生成邮件 HTML 内容。"""
    template_path = TEMPLATE_DIR / "email.html"
    if template_path.exists():
        template = template_path.read_text(encoding="utf-8")
    else:
        template = """<!DOCTYPE html>
<html>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:800px;margin:0 auto">
<h2 style="color:#202124">arXiv Daily Digest</h2>
<p style="color:#5f6368">Keywords: {{keywords}}</p>
<p style="color:#5f6368">{{count}} papers found</p>
<table style="width:100%;border-collapse:collapse">{{rows}}</table>
<p style="color:#9aa0a6;font-size:12px;margin-top:40px">Generated by arXiv Daily</p>
</body>
</html>"""

    rows = _render_paper_rows(papers)
    html = template.replace("{{keywords}}", ", ".join(keywords))
    html = html.replace("{{count}}", str(len(papers)))
    html = html.replace("{{rows}}", rows)
    return html


def send_email(config: dict, html_content: str) -> None:
    """通过 SMTP 发送邮件。"""
    email_cfg = config["email"]
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"arXiv Daily Digest"
    msg["From"] = email_cfg["username"]
    msg["To"] = email_cfg["to"]
    msg.attach(MIMEText(html_content, "html", "utf-8"))

    try:
        if email_cfg.get("use_ssl"):
            server = smtplib.SMTP_SSL(
                email_cfg["smtp_host"], email_cfg["smtp_port"], timeout=60
            )
        else:
            server = smtplib.SMTP(
                email_cfg["smtp_host"], email_cfg["smtp_port"], timeout=60
            )
            server.starttls()

        server.login(email_cfg["username"], email_cfg["password"])
        server.sendmail(email_cfg["username"], email_cfg["to"], msg.as_string())
        server.quit()
        logger.info("Email sent to %s", email_cfg["to"])
    except Exception:
        logger.exception("Failed to send email")
