"""样本论文数据，用于 --mock 模式快速测试 pipeline。"""


def get_mock_papers() -> list[dict]:
    return [
        {
            "id": "http://arxiv.org/abs/2605.10001",
            "title": "Large Language Models for Automated Code Generation: A Survey",
            "abstract": "Large language models (LLMs) have revolutionized software development by enabling automated code generation from natural language descriptions. This survey reviews recent advances in LLM-based code generation, including pre-training objectives, fine-tuning strategies, and evaluation benchmarks. We discuss challenges such as correctness, security, and efficiency.",
            "authors": ["Alice Chen", "Bob Smith", "Charlie Wang"],
            "categories": ["cs.SE", "cs.AI", "cs.CL"],
            "url": "http://arxiv.org/abs/2605.10001",
            "published": "2026-05-18",
            "summary": None,
        },
        {
            "id": "http://arxiv.org/abs/2605.10002",
            "title": "Neural Program Synthesis with Transformer-based Architectures",
            "abstract": "We present a novel approach to program synthesis using transformer-based neural architectures. Our model learns to generate programs from input-output examples by leveraging attention mechanisms and large-scale pre-training. Experiments on the Program Synthesis Benchmark show significant improvements over existing methods.",
            "authors": ["David Liu", "Eve Zhang"],
            "categories": ["cs.AI", "cs.SE"],
            "url": "http://arxiv.org/abs/2605.10002",
            "published": "2026-05-17",
            "summary": None,
        },
        {
            "id": "http://arxiv.org/abs/2605.10003",
            "title": "Fuzzing Deep Learning Libraries: Finding Bugs in TensorFlow and PyTorch",
            "abstract": "Deep learning libraries like TensorFlow and PyTorch are critical infrastructure for AI applications. We develop a fuzzing framework targeting numerical bugs and API misuse in these libraries. Our tool found 12 previously unknown bugs, 8 of which have been confirmed and fixed.",
            "authors": ["Frank Zhao", "Grace Li", "Henry Wu"],
            "categories": ["cs.SE", "cs.CR"],
            "url": "http://arxiv.org/abs/2605.10003",
            "published": "2026-05-18",
            "summary": None,
        },
        {
            "id": "http://arxiv.org/abs/2605.10004",
            "title": "Towards Robust Software Testing with Reinforcement Learning",
            "abstract": "Automated software testing remains challenging for complex systems. We propose a reinforcement learning framework that learns effective test generation policies. Our agent discovers edge cases and achieves higher code coverage compared to random and search-based baselines on Java and Python projects.",
            "authors": ["Iris Kim", "Jack Park"],
            "categories": ["cs.SE"],
            "url": "http://arxiv.org/abs/2605.10004",
            "published": "2026-05-16",
            "summary": None,
        },
        {
            "id": "http://arxiv.org/abs/2605.10005",
            "title": "Attention Mechanisms in Computer Vision: From CNNs to Vision Transformers",
            "abstract": "The evolution of attention mechanisms has transformed computer vision. This paper provides a comprehensive review of attention mechanisms, from channel and spatial attention in CNNs to self-attention in Vision Transformers. We analyze design principles, computational complexity, and performance trade-offs.",
            "authors": ["Kelly Brown", "Leo Davis"],
            "categories": ["cs.CV", "cs.AI"],
            "url": "http://arxiv.org/abs/2605.10005",
            "published": "2026-05-18",
            "summary": None,
        },
        {
            "id": "http://arxiv.org/abs/2605.10006",
            "title": "Secure Software Supply Chain: Detecting Malicious Packages in npm and PyPI",
            "abstract": "Software supply chain attacks have increased dramatically. We present a static analysis tool that detects malicious behavior in npm and PyPI packages by analyzing package metadata, install scripts, and API calls. Evaluation on 50,000 packages achieves 94% detection rate with 2% false positives.",
            "authors": ["Mia Garcia", "Noah Patel"],
            "categories": ["cs.CR", "cs.SE"],
            "url": "http://arxiv.org/abs/2605.10006",
            "published": "2026-05-17",
            "summary": None,
        },
        {
            "id": "http://arxiv.org/abs/2605.10007",
            "title": "Deep Learning for Medical Image Segmentation: A Systematic Review",
            "abstract": "Medical image segmentation is crucial for diagnosis and treatment planning. This systematic review covers U-Net variants, transformer-based architectures, and foundation models for segmentation across CT, MRI, and X-ray modalities. We benchmark 30 methods on 5 public datasets.",
            "authors": ["Olivia Tan", "Peter Nguyen"],
            "categories": ["cs.CV"],
            "url": "http://arxiv.org/abs/2605.10007",
            "published": "2026-05-18",
            "summary": None,
        },
        {
            "id": "http://arxiv.org/abs/2605.10008",
            "title": "Graph Neural Networks for Program Analysis and Optimization",
            "abstract": "Program representations as graphs enable powerful neural network-based analysis. We propose a graph neural network architecture that jointly performs program analysis and optimization. Our approach predicts optimal compiler passes for LLVM IR, achieving 5% speedup over default optimization levels.",
            "authors": ["Quinn Lee", "Rachel Huang"],
            "categories": ["cs.SE", "cs.AI"],
            "url": "http://arxiv.org/abs/2605.10008",
            "published": "2026-05-16",
            "summary": None,
        },
        {
            "id": "http://arxiv.org/abs/2605.10009",
            "title": "Adversarial Attacks on Code Completion Models: Vulnerabilities and Defenses",
            "abstract": "Code completion models based on LLMs are widely deployed. We systematically study adversarial attacks that cause these models to generate insecure or incorrect code completions. We propose training-time and inference-time defenses that reduce attack success rate from 78% to 12%.",
            "authors": ["Sam Zhou", "Tina Wilson"],
            "categories": ["cs.CR", "cs.AI", "cs.SE"],
            "url": "http://arxiv.org/abs/2605.10009",
            "published": "2026-05-18",
            "summary": None,
        },
        {
            "id": "http://arxiv.org/abs/2605.10010",
            "title": "Scaling Distributed Training of Large Language Models: Lessons from the Trenches",
            "abstract": "Training large language models at scale requires careful systems engineering. We share practical lessons from training models up to 175B parameters on thousands of GPUs, covering data parallelism, pipeline parallelism, checkpointing strategies, and failure recovery. Our insights reduce training time by 30%.",
            "authors": ["Uma Chen", "Victor Park", "Wendy Li"],
            "categories": ["cs.SY", "cs.AI", "cs.CL"],
            "url": "http://arxiv.org/abs/2605.10010",
            "published": "2026-05-18",
            "summary": None,
        },
    ]
